"""
6-mer filter activation analysis for sequence filters.

Tests all 4^6 = 4096 possible 6-mers through conv_incl and conv_skip
(no position bias — pure kernel response) then produces:

Fig 1 — Activation histograms: distribution of Softplus(conv(6mer)) across
         all 4096 6-mers, one panel per filter (4×5 grid, incl and skip).
         Shows sparsity: narrow = specific motif, broad = nonspecific.

Fig 2 — Empirical PWM logos: activation-weighted nucleotide frequencies
         across all 4096 6-mers → sequence logo per filter (incl and skip).
         Compare with conv-weight logos in filter_plots.py as a sanity check.

Fig 3 — Heatmap: for each filter show its top-20 activated 6-mers and
         their activation values (filters × top kmers).
"""

from pathlib import Path
import itertools
import math
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import logomaker
import sys

BASE = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(BASE))

OUT   = Path(__file__).resolve().parent
BASES = list("ACGT")

kmers = ["".join(k) for k in itertools.product(BASES, repeat=6)]  # 4096

# ── Load precomputed activations (generated by anaconda python with torch) ────
# To regenerate: run the block at the bottom of this file with anaconda python.
act_incl = np.load(OUT / "act_incl.npy")   # (4096, 20)
act_skip = np.load(OUT / "act_skip.npy")   # (4096, 20)
oh_array = np.load(OUT / "oh_array.npy")   # (4096, 4, 6)

print(f"act_incl: shape={act_incl.shape}  mean={act_incl.mean():.4f}  "
      f"max={act_incl.max():.4f}")
print(f"act_skip: shape={act_skip.shape}  mean={act_skip.mean():.4f}  "
      f"max={act_skip.max():.4f}")

N_FILTERS = 20

# ── Fig 1: Activation histograms ──────────────────────────────────────────────

for label, act in [("incl", act_incl), ("skip", act_skip)]:
    fig, axes = plt.subplots(4, 5, figsize=(14, 10))
    for fi, ax in enumerate(axes.flat):
        vals = act[:, fi]
        ax.hist(vals, bins=50, color="#4393c3" if label == "incl" else "#d6604d",
                alpha=0.75, edgecolor="none")
        frac_zero = (vals < 0.01).mean()
        ax.set_title(f"Filter {fi}  (zero={frac_zero:.0%})", fontsize=8)
        ax.set_xlabel("Activation", fontsize=7)
        ax.tick_params(labelsize=7)
    fig.suptitle(f"6-mer activation distributions — seq filters ({label})\n"
                 f"(zero = fraction of 6-mers with activation < 0.01)",
                 fontsize=10, y=1.02)
    fig.tight_layout()
    p = OUT / f"kmer_activation_hist_{label}.png"
    fig.savefig(p, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved {p.name}")

# ── Fig 2: IC-scaled logos (Oded's threshold approach) ───────────────────────
# Steps:
#  1. For each filter i, keep k-mers where activation > max_activation / 2
#  2. Count unweighted nucleotide frequencies at each position → f(b, l)
#  3. Compute IC: R(l) = 2 - H(l)  where H(l) = -sum(f*log2(f))
#  4. Scale: height(b, l) = f(b, l) * R(l)
#  5. Pass to logomaker (no center_values, no softmax)

def threshold_ic_pwm(act: np.ndarray) -> tuple[np.ndarray, list[dict]]:
    """Return IC-scaled (N_FILTERS, 6, 4) matrix + per-filter stats."""
    ic_mats = []
    stats   = []
    for fi in range(act.shape[1]):
        vals       = act[:, fi]           # (4096,)
        max_act    = vals.max()
        threshold  = max_act / 2
        mask       = vals > threshold
        n_active   = mask.sum()

        if n_active == 0:
            ic_mats.append(np.zeros((6, 4)))
            stats.append({"n_active": 0, "max_act": max_act, "threshold": threshold})
            continue

        # Unweighted frequency: (4096_active, 4, 6) → mean over active k-mers
        freq = oh_array[mask].mean(axis=0)   # (4, 6)  rows=ACGT, cols=positions

        # Shannon entropy and IC per position
        freq_safe = np.clip(freq, 1e-9, 1)
        H = -(freq_safe * np.log2(freq_safe)).sum(axis=0)   # (6,)
        R = 2 - H                                            # (6,) information content

        # IC-scaled heights: f(b,l) * R(l), shape (4, 6) → transpose to (6, 4)
        ic_scaled = (freq * R[None, :]).T    # (6, 4)  for logos
        ic_mats.append(ic_scaled)
        stats.append({"n_active": int(n_active), "max_act": float(max_act),
                      "threshold": float(threshold), "freq": freq})  # freq (4,6) for heatmap
    return np.array(ic_mats), stats   # (N_FILTERS, 6, 4)


LOGO_OPTS = dict(color_scheme="classic", vpad=0.05, width=0.9)

for label, act in [("incl", act_incl), ("skip", act_skip)]:
    ic_mats, stats = threshold_ic_pwm(act)   # (20, 6, 4)
    n_cols = 5
    n_rows = math.ceil(N_FILTERS / n_cols)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 2.5, n_rows * 1.8))

    print(f"\n{label} filters — threshold stats:")
    print(f"  {'filter':>7}  {'n_active':>9}  {'max_act':>9}  {'threshold':>10}")
    for fi, ax in enumerate(axes.flat):
        if fi >= N_FILTERS:
            ax.axis("off"); continue
        s  = stats[fi]
        df = pd.DataFrame(ic_mats[fi], columns=BASES,
                          index=range(1, 7))   # (6, 4), rows=positions
        print(f"  {fi:>7}  {s['n_active']:>9}  {s['max_act']:>9.4f}  {s['threshold']:>10.4f}")
        try:
            logomaker.Logo(df, ax=ax, **LOGO_OPTS)
        except Exception:
            ax.axis("off")
        ax.set_title(f"Filter {fi}  (n={s['n_active']})", fontsize=7)
        ax.set_xticks(range(6))
        ax.set_xticklabels(range(1, 7), fontsize=6)
        ax.tick_params(axis="y", labelsize=6)

    long_label = "inclusion" if label == "incl" else "skipping"
    fig.suptitle(f"Filter Sequence Logos scaled by Information Content"
                 f" — {long_label} sequence filters",
                 fontsize=10, y=1.02)
    fig.tight_layout()
    p = OUT / f"kmer_pwm_logos_{label}.png"
    fig.savefig(p, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved {p.name}")

# ── Fig 3: PWM heatmap — threshold-based unweighted frequencies ──────────────
# Input: raw frequency matrix (4×6) from active k-mers (activation > max/2).
# Each column sums to 1. Background = 0.25 (uniform).

for label, act in [("incl", act_incl), ("skip", act_skip)]:
    _, stats_h = threshold_ic_pwm(act)
    n_cols = 5
    n_rows = math.ceil(N_FILTERS / n_cols)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 2.2, n_rows * 1.6))
    cmap = "Blues" if label == "incl" else "Reds"
    long_label = "inclusion" if label == "incl" else "skipping"
    for fi, ax in enumerate(axes.flat):
        if fi >= N_FILTERS:
            ax.axis("off"); continue
        mat = stats_h[fi]["freq"]   # (4, 6) unweighted frequencies from active k-mers
        im  = ax.imshow(mat, aspect="auto", cmap=cmap, vmin=0, vmax=0.6)
        ax.set_xticks(range(6))
        ax.set_xticklabels(range(1, 7), fontsize=7)
        ax.set_yticks(range(4))
        ax.set_yticklabels(BASES, fontsize=7)
        ax.set_title(f"Filter {fi}  (n={stats_h[fi]['n_active']})", fontsize=7)
        plt.colorbar(im, ax=ax, fraction=0.08, pad=0.02).ax.tick_params(labelsize=5)
    fig.suptitle(f"Nucleotide frequency heatmap — {long_label} sequence filters\n"
                 f"(unweighted freq from active k-mers: activation > max/2; background = 0.25)",
                 fontsize=10, y=1.02)
    fig.tight_layout()
    p = OUT / f"kmer_pwm_heatmap_{label}.png"
    fig.savefig(p, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved {p.name}")

# ── Fig 4: Heatmap of top-20 activated 6-mers per filter ─────────────────────

TOP_K = 20

for label, act in [("incl", act_incl), ("skip", act_skip)]:
    # For each filter collect top-K kmer indices
    fig, axes = plt.subplots(4, 5, figsize=(16, 12))
    for fi, ax in enumerate(axes.flat):
        if fi >= N_FILTERS:
            ax.axis("off"); continue
        top_idx   = np.argsort(act[:, fi])[-TOP_K:][::-1]
        top_seqs  = [kmers[i] for i in top_idx]
        top_vals  = act[top_idx, fi]
        im = ax.imshow(top_vals[:, None], aspect="auto",
                       cmap="Blues" if label == "incl" else "Reds",
                       vmin=0)
        ax.set_yticks(range(TOP_K))
        ax.set_yticklabels(top_seqs, fontsize=6, fontfamily="monospace")
        ax.set_xticks([])
        ax.set_title(f"Filter {fi}", fontsize=8)
        plt.colorbar(im, ax=ax, fraction=0.08, pad=0.02).ax.tick_params(labelsize=6)
    fig.suptitle(f"Top-{TOP_K} activated 6-mers per filter — seq filters ({label})",
                 fontsize=10, y=1.02)
    fig.tight_layout()
    p = OUT / f"kmer_top_heatmap_{label}.png"
    fig.savefig(p, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved {p.name}")

print("\nDone.")
